
export const adminActions = {
    SET_AUTH: 'SET_AUTH',
    REMOVE_AUTH: 'REMOVE_AUTH',
    AUTH_ERROR: 'AUTH_ERROR',
    GET_COUNTS: 'GET_COUNTS',
    SET_ADMIN_VIEW_STUDENTS: 'SET_ADMIN_VIEW_STUDENTS',
    SET_ADMIN_VIEW_CLASSES: 'SET_ADMIN_VIEW_CLASSES'
}