
export const instructorActions = {
    SET_AUTH: 'SET_AUTH',
    REMOVE_AUTH_INSTRUCTOR: 'REMOVE_AUTH_INSTRUCTOR',
    AUTH_ERROR: 'AUTH_ERROR',
    SET_INSTRUCTOR_VIEW_CLASSES: 'SET_INSTRUCTOR_VIEW_CLASSES',
}