
export const studentActions = {
    SET_AUTH: 'SET_AUTH_STUDENT',
    REMOVE_AUTH_STUDENT: 'REMOVE_AUTH_STUDENT',
    AUTH_ERROR: 'AUTH_ERROR',
    SET_STUDENT_VIEW_CLASSES: 'SET_STUDENT_VIEW_CLASSES',
    SET_STUDENT_VIEW_CLASSES_TO_ENROLL: 'SET_STUDENT_VIEW_CLASSES_TO_ENROLL'
}